<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitff4378e222fd7c816e7d3c769a0d27d0
{
    public static $prefixLengthsPsr4 = array (
        'E' => 
        array (
            'East\\LaravelActivityfeed\\' => 25,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'East\\LaravelActivityfeed\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitff4378e222fd7c816e7d3c769a0d27d0::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitff4378e222fd7c816e7d3c769a0d27d0::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitff4378e222fd7c816e7d3c769a0d27d0::$classMap;

        }, null, ClassLoader::class);
    }
}
