<?php

namespace East\LaravelActivityfeed\Models\ActiveModels;

use East\LaravelActivityfeed\Facades\AfHelper;
use East\LaravelActivityfeed\Models\ActiveModelBase;
use East\LaravelActivityfeed\Models\ActivityFeedBaseModel;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;

/**
 * @property integer $id
 * @property integer $id_category
 * @property string $created_at
 * @property string $updated_at
 * @property string $name
 * @property string $slug
 * @property string $description
 * @property string $notification_template
 * @property string $email_subject
 * @property string $email_template
 * @property string $digest_template
 * @property string $admin_template
 * @property string $url_template
 * @property boolean $enabled
 * @property boolean $master_template
 * @property AfTemplate $id_parent
 * @property AfCategory $afCategory
 * @property AfEvent[] $afEvents
 * @property AfNotification[] $afNotifications
 * @property AfRule[] $afRules
 */
class AfTemplate extends ActiveModelBase
{
    /**
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'af_templates';

    /**
     * The "type" of the auto-incrementing ID.
     * 
     * @var string
     */
    protected $keyType = 'integer';

    /**
     * @var array
     */
    protected $fillable = ['id_category', 'created_at', 'updated_at', 'name', 'slug','description',
        'notification_template', 'email_subject','master_template','id_parent',
        'email_template', 'digest_template', 'admin_template',
        'enabled','url_template'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function afCategory()
    {
        return $this->belongsTo('East\LaravelActivityfeed\Models\ActiveModels\AfCategory', 'id_category');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function afEvents()
    {
        return $this->hasMany('East\LaravelActivityfeed\Models\ActiveModels\AfEvent', 'id_template');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function afNotifications()
    {
        return $this->hasMany('East\LaravelActivityfeed\Models\ActiveModels\AfNotification', 'id_template');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function afRules()
    {
        return $this->hasMany('East\LaravelActivityfeed\Models\ActiveModels\AfRule', 'id_template');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function afParent()
    {
        return $this->hasMany(AfTemplate::class, 'id_parent');
    }

    public function save(array $options = [])
    {


        //$this->id = request()->get('id');

/*        print_r(request()->all());

        print_r($this);

        print_r($this->exists);die();*/

        Cache::delete('af_template_files');
        parent::save($options); // TODO: Change the autogenerated stub
    }

}
